
services:
  events.feed:
    build:
      context: .
      dockerfile: Sportsdata.Consumer.Feed/Dockerfile
    restart: on-failure
    environment:
        PROFILE: Event
        ASPNETCORE_ENVIRONMENT: Prod
    volumes:
      - ./Sportsdata.Consumer.Feed/appsettings.json:/app/appsettings.json

  markets.feed:
    build:
      context: .
      dockerfile: Sportsdata.Consumer.Feed/Dockerfile
    restart: on-failure
    environment:
        PROFILE: Market
        ASPNETCORE_ENVIRONMENT: Prod
    volumes:
      - ./Sportsdata.Consumer.Feed/appsettings.json:/app/appsettings.json

  settlements.feed:
    build:
      context: .
      dockerfile: Sportsdata.Consumer.Feed/Dockerfile
    restart: on-failure
    environment:
        PROFILE: Settlement
        ASPNETCORE_ENVIRONMENT: Prod
    volumes:
      - ./Sportsdata.Consumer.Feed/appsettings.json:/app/appsettings.json

  enumerations.feed:
    build:
      context: .
      dockerfile: Sportsdata.Consumer.Feed/Dockerfile
    restart: on-failure
    environment:
      PROFILE: Enumeration
      ASPNETCORE_ENVIRONMENT: Prod
    volumes:
      - ./Sportsdata.Consumer.Feed/appsettings.json:/app/appsettings.json
  countries.feed:
    build:
      context: .
      dockerfile: Sportsdata.Consumer.Feed/Dockerfile
    restart: on-failure
    environment:
      PROFILE: Country
      ASPNETCORE_ENVIRONMENT: Prod
    volumes:
      - ./Sportsdata.Consumer.Feed/appsettings.json:/app/appsettings.json
  game-periods.feed:
    build:
      context: .
      dockerfile: Sportsdata.Consumer.Feed/Dockerfile
    restart: on-failure
    environment:
      PROFILE: GamePeriod
      ASPNETCORE_ENVIRONMENT: Prod
    volumes:
      - ./Sportsdata.Consumer.Feed/appsettings.json:/app/appsettings.json
  leagues.feed:
    build:
      context: .
      dockerfile: Sportsdata.Consumer.Feed/Dockerfile
    restart: on-failure
    environment:
      PROFILE: League
      ASPNETCORE_ENVIRONMENT: Prod
    volumes:
      - ./Sportsdata.Consumer.Feed/appsettings.json:/app/appsettings.json
  line-entities.feed:
    build:
      context: .
      dockerfile: Sportsdata.Consumer.Feed/Dockerfile
    restart: on-failure
    environment:
      PROFILE: LineEntity
      ASPNETCORE_ENVIRONMENT: Prod
    volumes:
      - ./Sportsdata.Consumer.Feed/appsettings.json:/app/appsettings.json
  market-lines.feed:
    build:
      context: .
      dockerfile: Sportsdata.Consumer.Feed/Dockerfile
    restart: on-failure
    environment:
      PROFILE: MarketLine
      ASPNETCORE_ENVIRONMENT: Prod
    volumes:
      - ./Sportsdata.Consumer.Feed/appsettings.json:/app/appsettings.json
  market-types.feed:
    build:
      context: .
      dockerfile: Sportsdata.Consumer.Feed/Dockerfile
    restart: on-failure
    environment:
      PROFILE: MarketType
      ASPNETCORE_ENVIRONMENT: Prod
    volumes:
      - ./Sportsdata.Consumer.Feed/appsettings.json:/app/appsettings.json                        
  sports.feed:
    build:
      context: .
      dockerfile: Sportsdata.Consumer.Feed/Dockerfile
    restart: on-failure
    environment:
      PROFILE: Sport
      ASPNETCORE_ENVIRONMENT: Prod
    volumes:
      - ./Sportsdata.Consumer.Feed/appsettings.json:/app/appsettings.json  
  teams.feed:
    build:
      context: .
      dockerfile: Sportsdata.Consumer.Feed/Dockerfile
    restart: on-failure
    environment:
      PROFILE: Team
      ASPNETCORE_ENVIRONMENT: Prod
    volumes:
      - ./Sportsdata.Consumer.Feed/appsettings.json:/app/appsettings.json          
